"""Markdown report writer for GitHub Step Summaries and PR Comments."""

from __future__ import annotations

from pathlib import Path

from preemptcore.core.models import ScanResult


def write_markdown_report(result: ScanResult, output_dir: Path) -> Path:
    """Write the scan result as a Markdown file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    out_path = output_dir / "report.md"

    high = sum(1 for f in result.findings if f.severity.value in ("high", "critical"))
    medium = sum(1 for f in result.findings if f.severity.value == "medium")
    low = sum(1 for f in result.findings if f.severity.value in ("low", "info"))
    qr = sum(1 for f in result.findings if f.quantum_relevance.value != "none")

    lines = [
        f"## PreemptCore Scan Report: {result.project_name}",
        "",
        "### Summary",
        "| Metric | Value |",
        "|--------|-------|",
        f"| **Q-Score** | **{result.q_score}/100** ({result.readiness_label}) |",
        f"| **Total Findings** | {len(result.findings)} |",
        f"| **Quantum-Relevant** | {qr} |",
        f"| **High / Critical** | {high} |",
        f"| **Medium** | {medium} |",
        f"| **Low / Info** | {low} |",
        "",
        "### Findings",
    ]

    if not result.findings:
        lines.append("No findings detected. Excellent job! 🚀")
    else:
        lines.extend([
            "| Severity | File | Line | Title | Category |",
            "|----------|------|------|-------|----------|",
        ])
        
        # Sort findings: severity (critical first)
        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        sorted_findings = sorted(result.findings, key=lambda f: severity_order.get(f.severity.value, 99))
        
        for f in sorted_findings:
            sev_badge = f"**{f.severity.value.upper()}**"
            file_name = f.file_path or "N/A"
            line_num = str(f.line_number) if f.line_number else "-"
            # Limit title length to avoid breaking tables
            title = f.title.replace("|", "-")
            category = f.category.replace("|", "-")
            lines.append(f"| {sev_badge} | `{file_name}` | {line_num} | {title} | {category} |")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [PreemptCore](https://github.com/preemptcore/preemptcore).*")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
